import { AppProvider } from "@/context/app";
import { AuthContextProvider } from "@/context/auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NotificationContextProvider } from "@/context/notification/index.notificationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NotificationContextProvider>
        <AuthContextProvider>
          <AppProvider>
            <body className={inter.className}>{children}</body>
          </AppProvider>
        </AuthContextProvider>
      </NotificationContextProvider>
    </html>
  );
}
